### ISSUE TITLE
ReferenceError: logSettings_1 is not defined when importing typegoose on aws EC2

### ISSUE THREAD

**Issue by mapircamera** [typegoose/typegoose#156]
## Versions

- NodeJS: 13.3.0
- Typegoose(NPM): 6.1.7
- mongoose: 5.8.0
- mongodb: 3.3.5

## What is the Problem?

When I run my nodejs server on aws ec2 instance, I get the following error. This error does not occur when I run the server locally. I've tried:

```ts
import { setLogLevel, LogLevels } from '@typegoose/typegoose';
setLogLevel(LogLevels.INFO);
```

in my server code, but I'm not sure of the best place to set this, and my impression was that if not set, logLevel would default to LogLevels.WARN

```
ReferenceError: logSettings_1 is not defined
at Object.<anonymous> (/home/ubuntu/mcc-web-server/node_modules/@typegoose/typegoose/src/typegoose.ts:13:3)
at Module._compile (module.js:635:30)
at Object.Module._extensions..js (module.js:646:10)
at Module.load (module.js:554:32)
at tryModuleLoad (module.js:497:12)
at Function.Module._load (module.js:489:3)
at Module.require (module.js:579:17)
at Module.Hook._require.Module.require (/home/ubuntu/.nvm/versions/node/v8.9.2/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:70:39)
at require (internal/module.js:11:18)
at Object.<anonymous> (/home/ubuntu/mcc-web-server/server.ts:3:1)
at Module._compile (module.js:635:30)
at Object.Module._extensions..js (module.js:646:10)
at Module.load (module.js:554:32)
at tryModuleLoad (module.js:497:12)
at Function.Module._load (module.js:489:3)
at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v8.9.2/lib/node_modules/pm2/lib/ProcessContainerFork.js:27:21)
```

## Code Example

This seems to occur when typegoose is imported/required in the compiled js of the node module.
typegoose.js
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const tslib_1 = require("tslib");
/* imports */
const mongoose = require("mongoose");
exports.mongoose = mongoose;
require("reflect-metadata");
const semver = require("semver");
const util_1 = require("util");
/* istanbul ignore next */
if (semver.lt(mongoose.version, '5.7.7')) {
    throw new Error('Please use mongoose 5.7.7 or higher');
}
if (semver.lt(process.version.slice(1), '8.10.0')) {
    logSettings_1.logger.warn('You are using a NodeJS Version below 8.10.0, Please Upgrade!');
}
const defaultClasses = require("./defaultClasses");
exports.defaultClasses = defaultClasses;
const globalOptions_1 = require("./globalOptions");
exports.setGlobalOptions = globalOptions_1.setGlobalOptions;
const constants_1 = require("./internal/constants");
const data_1 = require("./internal/data");
const errors_1 = require("./internal/errors");
const schema_1 = require("./internal/schema");
const utils_1 = require("./internal/utils");
const logSettings_1 = require("./logSettings");
var logSettings_2 = require("./logSettings");
exports.setLogLevel = logSettings_2.setLogLevel;
exports.LogLevels = logSettings_2.LogLevels;
```

server.ts
```ts
require('rootpath')();
// import { setLogLevel, LogLevels } from '@typegoose/typegoose';
// setLogLevel(LogLevels.INFO);
import { setGlobalOptions } from '@typegoose/typegoose';
setGlobalOptions({ globalOptions: { useNewEnum: true } });
import express = require('express');
import cors  = require('cors');
import bodyParser = require('body-parser');
import expressJwt = require('express-jwt');
import projectRouter from './routes/project.routes';
import imageRouter from './routes/image.routes';
import targetImageRouter from './routes/target_image.routes';
import userRouter from './routes/user.routes';
import pix4DTaskRouter from './routes/pix4d_task.routes';
import bandMixerTaskRouter from './routes/band_mixer_task.routes';
import calibrationTargetAnalysisTaskRouter from './routes/calibration_target_analysis_task.routes';
import tileRouter from './routes/tile.routes';
import pathToRegexp from 'path-to-regexp';
import mongoose from 'mongoose';
import AWS from 'aws-sdk';
import { truncate } from 'fs';

const config = require('config.json');
// mongoose.Promise = global.Promise;

const mongooseConnect = async () => {
    try{
        let connectOptions = {
            useNewUrlParser: true,
            // useCreateIndex: true,
            auto_reconnect: true,
            keepAlive: true,
            keepAliveInitialDelay: 300000,
            useUnifiedTopology: true
        }
        await mongoose.connect(config.connectionString, connectOptions);
        console.log('Mongoose initial connection successful')
    } catch (e) {
        console.log(e);
    }
}

const initAWS = async () => {
    let accessKeyId = config.AWS.accessKeyId;
    let secretAccessKey = config.AWS.secretAccessKey;
    let region = config.AWS.region;
    // let signatureVersion = 'v4';

    AWS.config.update(
        {
            accessKeyId,
            secretAccessKey,
            region,
            // signatureVersion
        }
    );
}

const initServer = async () => {

    await mongooseConnect();
    let db = mongoose.connection;
    db.on('connected', () => console.log('Mongoose connected'));
    db.on('error', e => console.log(e));
    db.on('disconnecting', () => console.log('Mongoose disconnecting'))
    db.on('disconnected', () => {
        console.log('Mongoose disconnected');
        // mongooseConnect();
    });
    db.on('reconnected', () => console.log('Mongoose successfully reconnected'));
    db.on('reconnectFailed', () => console.log('Mongoose reconnect failed'));
    db.on('close', () => console.log('Mongoose connection closed'));
    process.on('SIGINT', function() {
        db.close(() => {
            console.log('Mongoose connection disconnected through app termination');
            process.exit(0);
        });
    });

    await initAWS();
    const app = express();

    app.use(cors(
        // {
        //  origin: 'http://yourapp.com'
        // }
    ));
    app.use(bodyParser.urlencoded({limit: '50mb', extended: false }));
    app.use(bodyParser.json({limit: '50mb'}));
    // use JWT auth to secure the api, the token can be passed in the authorization header or querystring
    app.use(expressJwt({
        secret: config.secret,
        getToken: function (req) {
            if (req.headers.authorization && req.headers.authorization.split(' ')[0] === 'Bearer') {
                return req.headers.authorization.split(' ')[1];
            } else if (req.query && req.query.token) {
                return req.query.token;
            }
            return null;
        }
    }).unless({
        path: [
            '/users/login',
            '/users/register',
            // '/images',
            // '/projects',
            pathToRegexp('*/tiles/*')
        ]
    }));
    app.use('/tiles', tileRouter);
    app.use('/projects', projectRouter);
    app.use('/images', imageRouter);
    app.use('/target-images', targetImageRouter);
    app.use('/users', userRouter);
    app.use('/pix4d-tasks', pix4DTaskRouter);
    app.use('/band-mixer-tasks', bandMixerTaskRouter);
    app.use('/calibration-target-analysis-tasks', calibrationTargetAnalysisTaskRouter);


    // error handler
    app.use(function (err, req, res, next) {
        if (err.name === 'UnauthorizedError') {
            res.status(401).send('Invalid Token');
        } else {
            res.send("Connected to Server");
            throw err;
        }
    });

    // start server
    // var port = process.env.NODE_ENV === 'production' ? 80 : 4000;
    let port = 4000;
    // var host = process.env.NODE_ENV === 'production' ? '0.0.0.0' : '127.0.0.1';
    // var server = app.listen(port, host, function () {
    var server = app.listen(port, function () {
        console.log('Environment ' + process.env.NODE_ENV);
        console.log('Server listening on port ' + port);

    });
}

initServer();
```

user.ts - typegoose model
```ts
import mongoose from 'mongoose';
import { prop, Ref, getModelForClass, arrayProp } from '@typegoose/typegoose';
import { Project } from './project.model';


enum Role {
    ADMIN = 'admin',
    USER = 'user'
}

export interface projectDisplayData {
    projectId: string,
    showOnMap: boolean,
    index?: boolean,
    lut?: boolean,
    calibration?: boolean,
}

export class User {
    _id
    @prop({ enum: Role }) role?: Role;
    @prop() firstName?: string;
    @prop() lastName?: string;
    @prop({ unique: true }) email: string;
    @prop() hash: string;

    @prop() projectDisplayOrder? : projectDisplayData[];
    @arrayProp({
        ref: 'Project',
        foreignField: 'user',
        localField: '_id'
    })
    public projects: Project[];
}

export const UserModel = getModelForClass(User, {
    existingMongoose: mongoose,
    schemaOptions: {
        collection: 'users',
        timestamps: true
    }
})
```
## Do you know *why* it happenes?

*no*

**Comment by hasezoey** [comment]
> and my impression was that if not set, logLevel would default to LogLevels.WARN

yes, it is "WARN"

---

`logSettings_1` is a compiled output from typescript 

---

otherwise, i cant help because i dont use (and never used) AWS and as you say, it is not locally reproduceable

**Comment by OoDeLally** [comment]
I just solved the same error today by upgrading Typescript to `^3.7.0`.
The error came from a recursive type (e.g. `Foo = Foo[] | string`) used in a field of my typegoose doc. Somehow the type compilation didn't complain about it, but the import was failing with `ReferenceError: foo_1`.
Try upgrading to `^3.7.0`, hope it solves your problem.

**Comment by hasezoey** [comment]
@OoDeLally the minimal required typescript version to work with typegoose is 3.7
https://github.com/typegoose/typegoose#requirements

**Comment by OoDeLally** [comment]
Good to know :-) I guess I didn't take the time to RTFM, so I deserved my troubles. #
Now, it is possible that it is also OP's problem... let's see.

**Comment by WangShuXian6** [comment]
Has anyone solved the problem? I also have this problem, my project is deployed in tencent serverless.

**Comment by Dashue** [comment]
Hitting the same with nextjs

**Comment by Ben305** [comment]
I'm seeing the same problem with Typescript 3.8.3 and Node 10, but not with Node 12

**Comment by hasezoey** [comment]
while working on 7.0 i moved the tests from mocha & chai to jest (and ts-jest), while doing that i encountered the same error, it was strange at first but after trying to re-order the imports it magically worked (in the test where it occurred `prop` was imported from the file `prop.ts` directly and the following import from `typegoose.ts` was undefined (`typegoose_1 is undefined`) and after moving to import `prop` from `typegoose.ts` it started working again)
Environment while encountering this:
- env: jest (compiled with ts-jest)
- typescript: 3.8
- nodejs: 12.16
- system: linux mint 19.2 kernel: 5.3.0-40(or higher)

-> i have no clue what or why this is happening

**Comment by Ben305** [comment]
I just upgraded my Docker image to more recent version of Node 10 and the error is gone now.
