### ISSUE TITLE
class constructor cannot be invoked without 'new

### ISSUE THREAD

**Issue by singhsoldier13** [typegoose/typegoose#210]
## Versions

- typegoose: 6.4.0
- mongoose: 5.9.7

tsconfig.json
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "moduleResolution": "node",
    "pretty": true,
    "target": "es6",
    "noImplicitAny": true,
    "inlineSourceMap": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "sourceRoot": "./src",
    "outDir": "./build",
    "baseUrl": "./src"
  },
  "include": [
    "typings/index.d.ts",
    "./src/**/*.ts",
    "node_modules/typescript/lib/lib.es6.d.ts"
  ],
  "typeRoots": [
    "node_modules/@types"
  ],
  "types": [
    "express", "mongoose", "morgan", "body-parser", "compression", "helmet"
  ],
  "exclude":[
    "node_modules", "build"
  ]
}
```

```ts
export class PSPDrug {
  @prop({required: true})
  din: string;

  @prop({required: true})
  genericName: string;

  @prop({ref: ProgramProvider, _id: false})
  programProvider: ProgramProvider;

  @prop()
  brandName?: string;
}

export const PSPDrugModel = getModelForClass(PSPDrug);

const {_id: id} = await PSPDrugModel.create(PSPDrug);
const addedDrug = await PSPDrugModel.findById(id).exec();
```

getting this error:
```
(node:34494) UnhandledPromiseRejectionWarning: TypeError: Class constructor PSPDrug cannot be invoked without 'new'
    at /Users/xxx/projects/services-api/functions/psp/node_modules/mongoose/lib/helpers/promiseOrCallback.js:24:16
    at /Users/xxx/projects/services-api/functions/psp/node_modules/mongoose/lib/model.js:4860:21
    at /Users/xxx/projects/services-api/functions/psp/node_modules/mongoose/lib/model.js:3069:14
    at promiseOrCallback (/Users/xxx/projects/services-api/functions/psp/node_modules/mongoose/lib/helpers/promiseOrCallback.js:9:12)
    at Function.create (/Users/xxx/projects/services-api/functions/psp/node_modules/mongoose/lib/model.js:3066:10)
```

**Comment by hasezoey** [comment]
i dont really understand what you are trying to do with
> `const {_id: id} = await PSPDrugModel.create(PSPDrug);`

this should look like `.create({ din: "something", genericName: "something" })`

**Comment by singhsoldier13** [comment]
@hasezoey I had to change target to es5 in my tsconfig and got rid of the Class Constructor.... error.
I changed the above line to const result = await UserModel.create(user);
It is working as expected.

**Comment by hasezoey** [comment]
@singhsoldier13 the typegoose npm package is compiled and released as es6

**Comment by hasezoey** [comment]
because this issue didnt have any activity in the last month, it will be closed
