### ISSUE TITLE
Setting Type to an Enum Object for an Enum Property Throws an Error

### ISSUE THREAD

**Issue by DonIsaac** [typegoose/typegoose#282]
## Versions

- NodeJS: `13.12.0`
- Typegoose(NPM): ` 7.2.0` 
- mongoose: `5.9.17`
- mongodb: `3.5.8`

## What is the Problem?

Explicitly setting `type` setting in `@prop()` when using an enum throws an error, but no error is thrown when `type` is not set.

Here's the stack trace:
```
Error: Invalid type used for map!, got: "[object Object]" (Project.provider)Is the code transpiled with Babel or 'tsc --transpile-only' or 'ts-node --transpile-only'?
 See https://typegoose.github.io/typegoose/docs/decorators/prop/#enum
     at Object._buildPropMetadata (/wafir/node_modules/@typegoose/typegoose/src/prop.ts:238:15)
     at Object._buildSchema (/wafir/node_modules/@typegoose/typegoose/src/internal/schema.ts:55:7)
     at buildSchema (/wafir/node_modules/@typegoose/typegoose/src/typegoose.ts:129:9)
     at Object.getModelForClass (/wafir/node_modules/@typegoose/typegoose/src/typegoose.ts:75:58)
     at Object.<anonymous> (/wafir/src/models/project.model.ts:66:29)
     at Module._compile (internal/modules/cjs/loader.js:1118:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
     at Module.load (internal/modules/cjs/loader.js:982:32)
     at Function.Module._load (internal/modules/cjs/loader.js:875:14)
     at Module.require (internal/modules/cjs/loader.js:1022:19)
     at require (internal/modules/cjs/helpers.js:72:18)
     at Object.<anonymous> (/wafir/src/controllers/project.controller.ts:1:1)
     at Module._compile (internal/modules/cjs/loader.js:1118:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
     at Module.load (internal/modules/cjs/loader.js:982:32)
     at Function.Module._load (internal/modules/cjs/loader.js:875:14)
```

I set the `type` property because it suggests to in the known issues section of the [enum prop documentation](https://typegoose.github.io/typegoose/docs/decorators/prop/#enum). I'm also using the pattern described in the [refType section](https://typegoose.github.io/typegoose/docs/decorators/prop/#reftype) of the same page.

## Code Example

```ts
import { User } from './user.model';
import { prop, pre, getModelForClass, Ref, ReturnModelType, DocumentType, getName } from '@typegoose/typegoose'; // v7.2.0

export enum FeedbackProviders {
    /** @see JiraConfig */
    JIRA = 'JiraConfig'
}

export const getProviderName = (provider: string): FeedbackProviders => {
    if (!provider) throw new Error('provider cannot be null or undefined');

    let p = provider.trim().toLowerCase();
    switch (p) {
        case 'jira':
            return FeedbackProviders.JIRA;
        default:
            throw new Error(`Illegal provider name '${provider}'`);
    }
}

export class JiraConfig {
    @prop({ required: true})
    public projectKey!: string;

    @prop({ required: true})
    public url!: string;

    @prop({ required: true })
    public metaFieldId!: string;

    // TODO: Make this an array, allow for more than one issue type
    @prop({ required: true })
    public issueTypeName!: string;

}

// Aggregate of every config object
export type ProjectConfig = JiraConfig /* | GithubConfig | TrelloConfig | ... */

export class Project {

    // https://typegoose.github.io/typegoose/guides/advanced/reference-other-classes/#common-problems
    @prop({ ref: () => getName(User)})
    public user!: Ref<User>;

    // Follows this pattern:
    // https://typegoose.github.io/typegoose/docs/decorators/prop/#reftype
    @prop({
        enum: FeedbackProviders,
        type: FeedbackProviders, // <-- no errors are thrown when this is omitted
        required: true
    })
    public provider!: FeedbackProviders;

    @prop({
        _id: false,
        refPath: 'provider'
    })
    config!: ProjectConfig;
}

export const ProjectModel = getModelForClass(Project);

```

## Do you know *why* it happens?

No.

**Comment by hasezoey** [comment]
for an enum you need to set the type to either `Number` or `String` if compiled with `--transpile-only` or babel

(so using `type: FeedbackProviders` will **not** work)

**Comment by ggurkal** [comment]
@DonIsaac In that case you don't need to do anything except for omitting `type` or setting it to `String`, since `FeedbackProviders` enum consists of only strings.

The part in Known Issues you refer to applies only if you're using Babel as @hasezoey mentioned.

**Comment by hasezoey** [comment]
this question seems solved, so closing it
