### ISSUE TITLE
Geopoint fields not working anymore "Can't extract geo keys"

### ISSUE THREAD

**Issue by akash-rajput** [typegoose/typegoose#288]
## Versions

- NodeJS: 10.15.1
- Typegoose(NPM): 7.2.0 
- Typegoose(GIT): NA
- mongoose: 5.19.11
- mongodb: 4.2.3
- grahpql / type-graphql: graphql@14.6.0 / type-graphql@0.17.6

## What is the Problem?

We had a geopoint (`geo`) field in our schema which was working with 6.x.x but after upagrading to 7.x.x it started giving errors

## Code Example

```ts
// model
import { getSchemaOptions } from '@common/utils/typegoose';
import { getModelForClass, index, prop as Property, Ref } from '@typegoose/typegoose';
import { ObjectId } from 'bson';
import { Field as GqlField, Float, ObjectType as GqlType } from 'type-graphql';
import { User } from '../user/user.model';
import { Address } from '../_common/embed/address/address.embed';
import { IBusiness } from './business.interface';

@GqlType()
@index({ geo: '2dsphere' })
export class Business implements IBusiness {
  @GqlField(_type => String)
  readonly _id: ObjectId;

  @GqlField({ nullable: true })
  @Property({ required: false })
  name: string;

  @GqlField(_type => User, { nullable: true })
  @Property({ ref: 'User' })
  members: Ref<User>[];

  @GqlField(_type => Address, { nullable: true })
  @Property({ required: false })
  address: Address;

  @GqlField(_type => [Float], { nullable: true })
  @Property({ required: false })
  public geo: [number];
}

export const BusinessModel = getModelForClass(Business, getSchemaOptions());
```

```js
// stacktrace

{
  "message": "Can't extract geo keys: { _id: ObjectId('5edcd899ac1dad3f2ad95828'), members: [ ObjectId('5edccbe2cfe386283ff0497f') ], name: \"Vaijapur business\", address: { _id: ObjectId('5edcd899ac1dad3f2ad95829') }, geo: [ [ 74.7436299 ], [ 19.915527 ] ], createdAt: new Date(1591531673898), updatedAt: new Date(1591531673898), __v: 0 }  Point must only contain numeric elements",
  "locations": [
    {
      "line": 2,
      "column": 3
    }
  ],
  "path": [
    "addBusiness"
  ],
  "extensions": {
    "code": "INTERNAL_SERVER_ERROR",
    "exception": {
      "driver": true,
      "name": "MongoError",
      "index": 0,
      "code": 16755,
      "errmsg": "Can't extract geo keys: { _id: ObjectId('5edcd899ac1dad3f2ad95828'), members: [ ObjectId('5edccbe2cfe386283ff0497f') ], name: \"Vaijapur business\", address: { _id: ObjectId('5edcd899ac1dad3f2ad95829') }, geo: [ [ 74.7436299 ], [ 19.915527 ] ], createdAt: new Date(1591531673898), updatedAt: new Date(1591531673898), __v: 0 }  Point must only contain numeric elements",
      "stacktrace": [
        "MongoError: Can't extract geo keys: { _id: ObjectId('5edcd899ac1dad3f2ad95828'), members: [ ObjectId('5edccbe2cfe386283ff0497f') ], name: \"Vaijapur business\", address: { _id: ObjectId('5edcd899ac1dad3f2ad95829') }, geo: [ [ 74.7436299 ], [ 19.915527 ] ], createdAt: new Date(1591531673898), updatedAt: new Date(1591531673898), __v: 0 }  Point must only contain numeric elements",
        "    at Function.create (/home/akash/magicbill/server/node_modules/mongodb/lib/core/error.js:43:12)",
        "    at toError (/home/akash/magicbill/server/node_modules/mongodb/lib/utils.js:149:22)",
        "    at coll.s.topology.insert (/home/akash/magicbill/server/node_modules/mongodb/lib/operations/common_functions.js:265:39)",
        "    at /home/akash/magicbill/server/node_modules/mongodb/lib/core/connection/pool.js:404:18",
        "    at process._tickCallback (internal/process/next_tick.js:61:11)"
      ]
    }
  }
}
```
## Do you know *why* it happenes?

*no*

**Comment by akash-rajput** [comment]
**Just do confirm with**

doesn't work with 

```ts
  @Property({ required: false, type: Array })
  public geo: [[number]];
```

**Comment by hasezoey** [comment]
@akash-rajput since ~7.2 `mapProp` & `arrayProp` merged into `prop`, but as it has always been for an array you need to define either `items` or `type` with the correct type, for your case it would be `type: Number`

**Comment by andreialecu** [comment]
I think your problem could be related to the version of the index being used: https://docs.mongodb.com/manual/core/2dsphere/ 

You seem to be using legacy geojson format (version 2), but the index is probably created as version 3.

**Comment by akash-rajput** [comment]
@hasezoey yes that's what it is. Geo JSON point takes an array `[lng,lat]`. But yes passing number for  array field I didn't get it. For reference this solved my issue: 
```
geo: [ [ 74.7436299 ], [ 19.915527 ] ],
```
