### ISSUE TITLE
Cast to ObjectId failed for value when creating document with reference

### ISSUE THREAD

**Issue by j-waters** [typegoose/typegoose#418]
I have two models, `Account` and `Transaction`:

```typescript
// account.model.ts

export class Account extends defaultClasses.Base<string> {
    @prop()
    _id: string;

    @prop()
    name: string;
}

const AccountModel = getModelForClass(Account);

```

```typescript
// transaction.model.ts

export class Transaction extends defaultClasses.Base<string> {
    @prop()
    _id: string;

    @prop()
    name: string;

    @prop({ ref: Account })
    account: Ref<Account>;
}

const TransactionModel = getModelForClass(Transaction);

```

Creating an account is fine, but when I want to create a transaction, I want to be able to pass in an account id as well:

```typescript
TransactionModel({
            _id: "abc",
            name: "test",
            account: "acc1id",
        })
```

This doesn't work, and gives the following error:

```
Transaction validation failed: account: Cast to ObjectId failed for value "acc1id" at path "account" +3937ms
ValidationError: Transaction validation failed: account: Cast to ObjectId failed for value "acc1id" at path "account"
    at model.Document.invalidate (/srv/node_modules/mongoose/lib/document.js:2626:32)
    at model.$set (/srv/node_modules/mongoose/lib/document.js:1290:12)
    at model._handleIndex (/srv/node_modules/mongoose/lib/document.js:1019:14)
    at model.$set (/srv/node_modules/mongoose/lib/document.js:960:22)
    at model.Document (/srv/node_modules/mongoose/lib/document.js:150:12)
    at model.Model (/srv/node_modules/mongoose/lib/model.js:106:12)
    at new model (/srv/node_modules/mongoose/lib/model.js:4689:15)
    at /srv/node_modules/mongoose/lib/model.js:3055:22
    at /srv/node_modules/mongoose/lib/model.js:3091:7
    at Array.forEach (<anonymous>)
    at /srv/node_modules/mongoose/lib/model.js:3090:15
    at /srv/node_modules/mongoose/lib/helpers/promiseOrCallback.js:31:5
    at new Promise (<anonymous>)
    at promiseOrCallback (/srv/node_modules/mongoose/lib/helpers/promiseOrCallback.js:30:10)
    at Function.create (/srv/node_modules/mongoose/lib/model.js:3025:10)
```

I can create a transaction fine if I first fetch the account with the id and use that (`account: fetchedAccount`) but using a string doesn't work (`account: fetchedAccount._id`). **Ideally I'd like to create a transaction without having to fetch the full account**.

## Versions

- typegoose: 7.4.2
- mongoose: 5.10.15

**Comment by hasezoey** [comment]
if you change your target `_id` type (in this case `string`) you also need to set it on the reference property:
```ts
@prop({ ref: Class, type: String })
public property: Ref<Class, string>;
```

**Comment by j-waters** [comment]
Ah that makes perfect sense thanks!
