### ISSUE TITLE
population of related model gives - Option "ref" for "Game.topic" is null/undefined 

### ISSUE THREAD

**Issue by dcsan** [typegoose/typegoose#427]
## Versions

```
npm ls mongoose
bot@1.0.0 /Users/dc/dev/ten/puzzleparty/server
└── mongoose@5.10.18

npm ls @typegoose/typegoose
bot@1.0.0 /Users/dc/dev/ten/puzzleparty/server
└── @typegoose/typegoose@7.4.4

npm -v
6.14.9
node -v
v14.5.0
npx tsc -v
Version 4.1.2
```

## What is the Problem?
In using mongoose basic populate methods to hydrate a linked model:

https://typegoose.github.io/typegoose/docs/api/virtuals/#virtual-populate

I am getting a "ref" is undefined for trying to link to a related Class.

Error: Option "ref" for "Game.topic" is null/undefined! [E005]

## Code Example

I have game and topic classes I am trying to 'populate' as below.
So I could use `game.topic` in a result set.
But at compile time I get an error with this.

```ts

class Topic {

  @prop({
    ref: () => Game,
    foreignField: 'topic',
    localField: '_id',
    justOne: true
  })
  public game: Ref<Game>

 ...
}

class Game {
  @prop({ ref: () => Topic })
  public topic: Ref<Topic>
 ...
}
```

The full error is:

```
Error: Option "ref" for "Game.topic" is null/undefined! [E005]
    at Object.processProp (/Users/dc/dev/ten/puzzleparty/server/node_modules/@typegoose/typegoose/src/internal/processProp.ts:141:7)
    at Object._buildSchema (/Users/dc/dev/ten/puzzleparty/server/node_modules/@typegoose/typegoose/src/internal/schema.ts:58:7)
    at buildSchema (/Users/dc/dev/ten/puzzleparty/server/node_modules/@typegoose/typegoose/src/typegoose.ts:140:9)
    at Object.getModelForClass (/Users/dc/dev/ten/puzzleparty/server/node_modules/@typegoose/typegoose/src/typegoose.ts:84:58)
    at Object.<anonymous> (/Users/dc/dev/ten/puzzleparty/server/src/models/Game.ts:93:19)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Module._compile (/Users/dc/dev/ten/puzzleparty/server/node_modules/source-map-support/source-map-support.js:547:25)
    at Module.m._compile (/private/var/folders/wl/fsxhspwn0351_lx_55rkwgwc0000gn/T/ts-node-dev-hook-467125897881844.js:57:33)
    at Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at require.extensions.<computed> (/private/var/folders/wl/fsxhspwn0351_lx_55rkwgwc0000gn/T/ts-node-dev-hook-467125897881844.js:59:20)
    at Object.nodeDevHook [as .ts] (/Users/dc/dev/ten/puzzleparty/server/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/Users/dc/dev/ten/puzzleparty/server/src/models/Topic.ts:12:1)
```

## Do you know *why* it happens?

*no*
Only thought was that if there is a circular dependency between the types since I have to import one class into the other.

**Comment by dcsan** [comment]
I also tried with `required: true`

```
class Game {
  @prop({ required: true, ref: () => Topic })
```

but this still gives the same error and also results in some VScode errors on types when creating the game where the topic param is redlined

![image](https://user-images.githubusercontent.com/514002/100890718-65448100-346d-11eb-89c3-55adf8c48919.png)


```
No overload matches this call.
  The last overload gave the following error.
    Type 'Topic' is not assignable to type 'string | ObjectId | { game: string | ObjectId | { topic: string | ObjectId | ...; mode?: string | undefined; input?: string | undefined; turns?: string | number | undefined; ... 5 more ...; message: { ...; }; }; ... 10 more ...; status?: string | undefined; }'.
      Type 'Topic' is not assignable to type '{ game: string | ObjectId | { topic: string | ObjectId | ...; mode?: string | undefined; input?: string | undefined; turns?: string | number | undefined; hints?: string | ... 1 more ... | undefined; ... 4 more ...; message: { ...; }; }; ... 10 more ...; status?: string | undefined; }'.
        Types of property 'game' are incompatible.
          Type 'Ref<Game, ObjectId | undefined>' is not assignable to type 'string | ObjectId | { topic: string | ObjectId | { game: string | ObjectId | ...; name?: string | undefined; title?: string | undefined; description?: string | undefined; ... 7 more ...; status?: string | undefined; }; ... 8 more ...; message: { ...; }; }'.
            Type 'undefined' is not assignable to type 'string | ObjectId | { topic: string | ObjectId | { game: string | ObjectId | ...; name?: string | undefined; title?: string | undefined; description?: string | undefined; ... 7 more ...; status?: string | undefined; }; ... 8 more ...; message: { ...; }; }'.

....
```

**Comment by hasezoey** [comment]
>  But at compile time I get an error with this.

this is an *runtime* error, not an *compile-time* error

are the 2 classes in the same file, or in different ones?

**Comment by dcsan** [comment]
> this is an runtime error, not an compile-time error

OK

the two classes are in different files, using imports. that was why i thought maybe circular deps

I'm using

```
import { Topic, TopicManager, TopicModel } from './Topic'
```

**Comment by hasezoey** [comment]
@dcsan try if using strings for `ref` (use the final model name) work, when it does, it is an circular deps problem

**Comment by fjplaurr** [comment]
Some minutes ago, I was having the exactly the same issue: 
Circular deps and getting E005 error.

@hasezoey I tried using string for ref and works.  

Fyi: I also tried to avoid hardcoding using what's [recommended in the docs](https://typegoose.github.io/typegoose/docs/guides/advanced/reference-other-classes/#common-problems):
_"since 7.0 it is recommended to use "ref: getName(Class)" to dynamically get the name"_
But using getName didn't work. I got: 'Cannot read property 'constructor' of undefined'

**Comment by hasezoey** [comment]
@fjplaurr sorry the documentation on this is a *bit* outdated, `getName` is also used in the type-functions to get the name deferred, and this is also the reason why it needs to get the class in the first place (TL;DR: if the arrow-functions dont work, then using `getName` directly will not work either)

**Comment by brucruz** [comment]
I am getting the same error myself.
I am using typegoose associated with type-graphql.

**User Model**
```
@ObjectType({ description: 'The Users model' })
export class User {
  @Field(() => ObjectIdScalar)
  readonly _id: ObjectId;

  @Field(() => String, { description: 'User name' })
  @prop({ trim: true, required: true })
  name: string;

  @Field({ description: 'User surname', nullable: true })
  @prop({ trim: true })
  surname?: string;

  @Field({ description: 'User email to be used on login' })
  @prop({ trim: true, required: true, unique: true })
  email: string;

  @prop()
  password?: string;

  @Field(_type => [Post])
  @prop({ type: () => Post, default: [] })
  posts: Post[];

  @Field({ description: 'User creation date' })
  createdAt?: Date;
  
  @Field({ description: 'User last update date', nullable: true })
  updatedAt?: Date;

  static async encryptPassword(password: string): Promise<string> {
    return hash(password);
  }

  public async authenticate(plainText: string) {
    try {
      return verify(this.password || '', plainText);
    } catch (err) {
      return false;
    }
  }
}

export const UserModel = getModelForClass(User, { schemaOptions: {
  collection: 'users',
  timestamps: {
    createdAt: 'createdAt',
    updatedAt: 'createdAt',
  },
} });
```

**Post Model**
```
@ObjectType({ description: 'The Posts model' })
export class Post {
  @Field(() => ObjectIdScalar)
  readonly _id: ObjectId;

  @Field(() => String, { description: 'Post title' })
  @prop({ trim: true, required: true })
  title: string;

  @Field({ description: 'Post content' })
  @prop({ required: true })
  content: string;

  @Field({ description: 'Number of likes this post has received', defaultValue: 0 })
  @prop({ default: 0 })
  likes?: number;

  @Field(_type => User)
  @prop({ ref: User, required: true })
  creator: Ref<User>;

  @Field({ description: 'Post creation date' })
  createdAt?: Date;
  
  @Field({ description: 'Post last update date', nullable: true })
  updatedAt?: Date;
}

export const PostModel = getModelForClass(Post, { schemaOptions: {
  collection: 'posts',
  timestamps: {
    createdAt: 'createdAt',
    updatedAt: 'createdAt',
  },
} });
```

**This is the error I'm getting.**
```
Error: Option "ref" for "Post.creator" is null/undefined! [E005]
    at Object.processProp (/Users/brunocruz/code/creators-communities-project/server/node_modules/@typegoose/typegoose/src/internal/processProp.ts:141:7)
    at Object._buildSchema (/Users/brunocruz/code/creators-communities-project/server/node_modules/@typegoose/typegoose/src/internal/schema.ts:58:7)
    at buildSchema (/Users/brunocruz/code/creators-communities-project/server/node_modules/@typegoose/typegoose/src/typegoose.ts:140:9)
    at Object.getModelForClass (/Users/brunocruz/code/creators-communities-project/server/node_modules/@typegoose/typegoose/src/typegoose.ts:84:58)
    at Object.<anonymous> (/Users/brunocruz/code/creators-communities-project/server/src/models/Post.ts:48:26)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Module._compile (/Users/brunocruz/code/creators-communities-project/server/node_modules/source-map-support/source-map-support.js:547:25)
    at Module.m._compile (/private/var/folders/s8/1hc7w_9577qc8ltsl4w7vd5h0000gn/T/ts-node-dev-hook-1372691903688159.js:57:33)
    at Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at require.extensions.<computed> (/private/var/folders/s8/1hc7w_9577qc8ltsl4w7vd5h0000gn/T/ts-node-dev-hook-1372691903688159.js:59:20)
    at Object.nodeDevHook [as .ts] (/Users/brunocruz/code/creators-communities-project/server/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/brunocruz/code/creators-communities-project/server/src/models/User.ts:5:1)
[ERROR] 18:24:43 Error: Option "ref" for "Post.creator" is null/undefined! [E005]
```

Any ideas of whats should I do to correct this error?

**Comment by hasezoey** [comment]
@brucruz can you confirm that all the required tsconfig options are set properly? (`target` being `es6` or higher, `experimentalDecorators` being `true` and `emitDecoratorMetadata` being `true`)

and can you confirm that this is not an circular dependency issue?

**Comment by dcsan** [comment]
so to check the circular deps he should use a string, eg 

`  creator: Ref<User>; `  
would be just 
`  creator: "User";`

correct? (or else put both models into one file, would that also solve it? I recall its the imports and js making a temporary definition to resolve during processing step)

**Comment by hasezoey** [comment]
no, its
```ts
@prop({ ref: 'TheModelName' })
public yourProp: Ref<Class>;
```
