### ISSUE TITLE
Example in Basic Usage section in Readme.md is not working

### ISSUE THREAD

**Issue by meepeek** [typegoose/typegoose#551]
## Versions

- System: linux 
- NodeJS: 15.11.0
- Typescript: 0.0.0

- Compiler / Transpiler: ts-node 9.1.1 
- Typegoose(NPM): 7.4.2 
- Typegoose(GIT): commithash
- mongoose: 5.10.18 
- mongodb: 4.4.6

## What is the Problem?

Copy the sample code in Readme.md to test and it throws error as follow
```
Error: "User.name"'s Type is invalid! Type is: "undefined" [E009]
    at Object.processProp (/home/thee/project/mass-surveillance-investing/msi-scoring/node_modules/@typegoose/typegoose/src/internal/processProp.ts:266:11)
    at Object._buildSchema (/home/thee/project/mass-surveillance-investing/msi-scoring/node_modules/@typegoose/typegoose/src/internal/schema.ts:58:7)
    at buildSchema (/home/thee/project/mass-surveillance-investing/msi-scoring/node_modules/@typegoose/typegoose/src/typegoose.ts:140:9)
    at Object.getModelForClass (/home/thee/project/mass-surveillance-investing/msi-scoring/node_modules/@typegoose/typegoose/src/typegoose.ts:84:58)
    at Object.<anonymous> (/home/thee/project/mass-surveillance-investing/msi-scoring/typegoose/test.ts:12:19)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Module.m._compile (/home/thee/app/nodejs-15.11/lib/node_modules/ts-node/src/index.ts:1056:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Object.require.extensions.<computed> [as .ts] (/home/thee/app/nodejs-15.11/lib/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at main (/home/thee/app/nodejs-15.11/lib/node_modules/ts-node/src/bin.ts:198:14)
    at Object.<anonymous> (/home/thee/app/nodejs-15.11/lib/node_modules/ts-node/src/bin.ts:288:3)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
```

## Code Example

```ts
import { prop, getModelForClass } from '@typegoose/typegoose';
import * as mongoose from 'mongoose';

class User {
  @prop()
  public name?: string;

  @prop({ type: () => [String] })
  public jobs?: string[];
}

const UserModel = getModelForClass(User); // UserModel is a regular Mongoose Model with correct types

(async () => {
  await mongoose.connect('mongodb://localhost:27017/', { useNewUrlParser: true, useUnifiedTopology: true, dbName: 'test' });

  const { _id: id } = await UserModel.create({ name: 'JohnDoe', jobs: ['Cleaner'] } as User); // an "as" assertion, to have types for all properties
  const user = await UserModel.findById(id).exec();

  console.log(user); // prints { _id: 59218f686409d670a97e53e0, name: 'JohnDoe', __v: 0 }
})();
```

## Do you know *why* it happens?

*no*

---

**Comment by meepeek** [comment]
fixed by setting "emitDecoratorMetadata": true in the tsconfig.json

I think it should be putting in readme if the setting is required

**Comment by smolinari** [comment]
@meepeek - You really should ask questions in Discussions or in the Discord first, before adding issues. If after the discussions you  do have a proper issue, you can add it here. 

Discussions: https://github.com/typegoose/typegoose/discussions
Discord: https://discord.gg/UaCtwrzs

Scott

**Comment by hasezoey** [comment]
@meepeek it is documented, but got moved into the quick-start-guide to reduce duplicate maintenance (duplicate requirements sections), so it can be found [here](https://typegoose.github.io/typegoose/docs/guides/quick-start-guide/#requirements)

PS: that option is not *strictly* required
