### ISSUE TITLE
isRefType not working properly

### ISSUE THREAD

**Issue by Theoblanc** [typegoose/typegoose#569]
## Versions

- System: macos
- NodeJS: 14.16.0-alpine
- Typescript: 4.3.2
- Compiler / Transpiler: tsc 
- Typegoose(NPM): ^7.6.0 
- mongoose: ^5.10.18 
- mongodb: latest
- nestjs / nestjs-typegoose:  ^7.5.1 / ^7.1.38 
- grahpql / type-graphql: ^15.5.0

## What is the Problem?
expect the guard to return false as the object received is not ref type, but the guard returns true and the following error happens
```bash
nest       | TypeError: notification.toHexString is not a function
nest       |     at /usr/src/app/dist/modules/notifications/services/notifications.service.js:53:71
nest       |     at Array.map (<anonymous>)
nest       |     at NotificationsService.findAll (/usr/src/app/dist/modules/notifications/services/notifications.service.js:50:52)
nest       |     at NotificationsResolver.findAllNotification (/usr/src/app/dist/modules/notifications/resolvers/notifications.resolver.js:31:29)
nest       |     at /usr/src/app/node_modules/@nestjs/core/helpers/external-context-creator.js:69:33
nest       |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

## Code Example
User Schema
```ts
@ObjectType()
@Exclude()
@ModelOptions({
  schemaOptions: {
    collection: 'users',
    timestamps: true,
  },
})
export class User extends DocumentCT {
  @Field(() => [Notification], { nullable: true })
  @prop({ ref: 'Notification' })
  @Expose()
  @Type(() => Notification)
  notifications?: Ref<Notification>[];
}
```

code with error
```ts
    const user = plainToClass(User, savedUser)
    const notificationIds: string[] = user.notifications.map((notification) => {
      console.log(notification);
      console.log(isRefType(notification));
      return isRefType(notification) ? notification.toHexString() : notification.id;
    });
```
bash
```bash
nest       | Notification {
nest       |   id: '60d93b114a509d0020e51a12',
nest       |   createdAt: undefined,
nest       |   updatedAt: undefined,
nest       |   type: undefined,
nest       |   seq: undefined,
nest       |   title: undefined,
nest       |   content: undefined
nest       | }
nest       | true
nest       | [Nest] 159   - 06/28/2021, 7:16:22 AM   notification.toHexString is not a function +15ms
nest       | TypeError: notification.toHexString is not a function
nest       |     at /usr/src/app/dist/modules/notifications/services/notifications.service.js:53:71
nest       |     at Array.map (<anonymous>)
nest       |     at NotificationsService.findAll (/usr/src/app/dist/modules/notifications/services/notifications.service.js:50:52)
nest       |     at NotificationsResolver.findAllNotification (/usr/src/app/dist/modules/notifications/resolvers/notifications.resolver.js:31:29)
nest       |     at /usr/src/app/node_modules/@nestjs/core/helpers/external-context-creator.js:69:33
nest       |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

## Do you know *why* it happens?

*no*

---

**Comment by hasezoey** [comment]
should be fixed in e3a3bf7150cd9569b974c7c4322d35f66ec03957, but as an downside, an second parameter will be needed to specify what the reftype is to test for on runtime
