### ISSUE TITLE
How to trace errors correctly?

### ISSUE THREAD

**Issue by Tobjoern** [typegoose/typegoose#617]
Hey, I have a general question regarding error tracing.
In my current express app, I noticed that typegoose errors weren't printed in the stack correctly.
I prepared a reproduction here: https://github.com/Tobjoern/typegoose-virtual-autopop-bug.
The function 'doWork' throws an error in line 14, but this line is nowhere to be found in the error log.
```
Error: ExampleEntity validation failed: name: Path `name` is required.
    at ValidationError.inspect (/home/tobias/coding/explorations/typegoose-virtual-autopop-bug/node_modules/mongoose/lib/error/validation.js:48:26)
    at internal/per_context/primordials.js:23:32
    at formatValue (internal/util/inspect.js:783:19)
    at inspect (internal/util/inspect.js:337:10)
    at formatWithOptionsInternal (internal/util/inspect.js:2017:40)
    at formatWithOptions (internal/util/inspect.js:1899:10)
    at console.value (internal/console/constructor.js:330:14)
    at console.warn (internal/console/constructor.js:363:61)
    at Object.<anonymous> (/home/tobias/coding/explorations/typegoose-virtual-autopop-bug/src/main.ts:44:17)
    at Generator.throw (<anonymous>)
    at rejected (/home/tobias/coding/explorations/typegoose-virtual-autopop-bug/src/main.ts:5:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  errors: {
    name: ValidatorError: Path `name` is required.
        at validate (/home/tobias/coding/explorations/typegoose-virtual-autopop-bug/node_modules/mongoose/lib/schematype.js:1264:13)
        at /home/tobias/coding/explorations/typegoose-virtual-autopop-bug/node_modules/mongoose/lib/schematype.js:1247:7
        at Array.forEach (<anonymous>)
        at SchemaString.SchemaType.doValidate (/home/tobias/coding/explorations/typegoose-virtual-autopop-bug/node_modules/mongoose/lib/schematype.js:1197:14)
        at /home/tobias/coding/explorations/typegoose-virtual-autopop-bug/node_modules/mongoose/lib/document.js:2662:18
        at processTicksAndRejections (internal/process/task_queues.js:77:11) {
....
}
```

It seems that it's lost in a bunch of error wrappers.
In larger projects it becomes increasingly hard to find out where the error occured exactly.
Am I handling the error incorrectly, or is this an issue with typegoose?
For comparison, I prepared an error in lines 19-21, when commented out, it reads:
`TypeError: Cannot set property 'b' of null
    at anotherFunc (/home/tobias/coding/explorations/typegoose-virtual-autopop-bug/src/main.ts:21:8)`

I'm looking forward to your answers.

## Versions

- System: linux
- NodeJS: v14.17.0
- Typescript: 4.4.2
- Typegoose(NPM): 9.0.1
- mongoose: 6.0.7
---

**Comment by hasezoey** [comment]
next time please directly use triple-quotes, as can be seen in [Mastering Markdown](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown)'s `Syntax Highlighting`

---

> Error: ExampleEntity validation failed: name: Path `name` is required.

this is not a Error that typegoose throws, this is a native mongoose error

typegoose errors can be identified by having `typegoose/typegoose` in the stacktrace AND / OR having a Error ID (`E001`), see [This Guide for more](https://typegoose.github.io/typegoose/docs/guides/error-warning-details)

as for the error you are having, your schema / model / class `ExampleEntity` failed because property `name` is not provided but required "*at somewhere*"

---

aside from that all, the error seems to be very long and convoluted (there is nothing typegoose can do about it), also i am not quite sure, but it seems like source-mapping is not activated or not behaving correctly (it needs to be enabled & outputted by tsc, and in nodejs either have module `source-map-support/enable` imported or having set node option `--enable-source-maps` on newer versions)

---

PS: i will move this issue to a discussion
