### ISSUE TITLE
Maximum call stack exceeded as of today with untouched project?

### ISSUE THREAD

**Issue by michaelbats** [typegoose/typegoose#70]
## Versions

- NodeJS: 10.16.3
- Typegoose(NPM): 6.0.1 and 6.0.3
- Typegoose(GIT):  //
- mongoose: 5.6.11
- mongodb: 0.0.0

## Error

```
RangeError: Maximum call stack size exceeded
    at Object.initAsArray (api\node_modules\@typegoose\typegoose\lib\internal\utils.js:76:30)
    at data_1.decoratorCache.get.decorators.set (api\node_modules\@typegoose\typegoose\lib\prop.js:62:19)
    at Object._buildSchema (api\node_modules\@typegoose\typegoose\lib\internal\schema.js:33:13)
    at Object.buildSchema (api\node_modules\@typegoose\typegoose\lib\typegoose.js:126:20)
```

## Do you know *why* it happenes?

*no*

Using together with nestjs / nestjs-typegoose -- the thing is I haven't worked at all on this API since last week. I'll keep adding more details as I find them but thought I'd post a barebones issue here first and see if others experience it as well or if it's just me.

**Comment by oktapodia** [comment]
same one I was telling you about @hasezoey

**Comment by michaelbats** [comment]
The in-production version of my API has completely crashed with this error although I haven't deployed/updated a version since last week. Something has gone terribly wrong.
