### ISSUE TITLE
Discriminator Inheritance virtual field error

### ISSUE THREAD

**Issue by OoDeLally** [typegoose/typegoose#80]
## Versions

- NodeJS: 12.10.0
- Typegoose(NPM): 6.0.1
- mongoose: 5.7.3
- mongodb: 4.2.0

## Code Example

I created a special foobar minimal repo for it: https://github.com/OoDeLally/typegoose-inheritance-bug. Just download it and run it (`npm i && npm start`). It should crash with the following error.

```
Error [MongooseError]: If you are populating a virtual, you must set the localField and foreignField options
    at new MongooseError (/home/foobar/server/node_modules/mongoose/lib/error/mongooseError.js:10:11)
    at getModelsMapForPopulate (/home/foobar/server/node_modules/mongoose/lib/helpers/populate/getModelsMapForPopulate.js:137:14)
    at populate (/home/foobar/server/node_modules/mongoose/lib/model.js:4091:21)
    at _populate (/home/foobar/server/node_modules/mongoose/lib/model.js:4061:5)
    at /home/foobar/server/node_modules/mongoose/lib/model.js:4036:5
    at Object.promiseOrCallback (/home/foobar/server/node_modules/mongoose/lib/utils.js:249:12)
    at Function.Model.populate (/home/foobar/server/node_modules/mongoose/lib/model.js:4035:16)
    at cb (/home/foobar/server/node_modules/mongoose/lib/query.js:1914:17)
    at /home/foobar/server/node_modules/mongodb/lib/operations/execute_operation.js:75:17
    at executeCallback (/home/foobar/server/node_modules/mongodb/lib/operations/execute_operation.js:68:9)
    at handleCallback (/home/foobar/server/node_modules/mongodb/lib/utils.js:129:55)
    at /home/foobar/server/node_modules/mongodb/lib/operations/to_array.js:36:13
    at handleCallback (/home/foobar/server/node_modules/mongodb/lib/utils.js:129:55)
    at completeClose (/home/foobar/server/node_modules/mongodb/lib/cursor.js:859:16)
    at Cursor.close (/home/foobar/server/node_modules/mongodb/lib/cursor.js:878:12)
    at /home/foobar/server/node_modules/mongodb/lib/operations/to_array.js:35:25 {
  message: 'If you are populating a virtual, you must set the localField and foreignField options',
  name: 'MongooseError'
}
```

I did NOT forget a field.
Many slight changes seem to solve the problem, and some of these seem unrelated to the cause.

## Do you know *why* it happens?

I have some clues. I've checked how it happens inside `typegoose` and `mongoose`.
It seems like the general schema created by `typegoose` is correct, and the virtual fields have the correct options values (`ref`, `localField`, `foreignField` ).
At the end of the `_buildSchema` function (in `typegoose/lib/internal/schema.js`), `sch.virtuals.get('bar').get('foo')` seems correctly set.

However, once mongoose picks up the schema (`getModelsMapForPopulate` in `mongoose/lib/helpers/populate/getModelsMapForPopulate.js`), the `options` object is empty, and that is why `mongoose` complains about missing fields. `sch.virtuals.get('bar').get('foo')` still exists but the `options` object is empty.

I have no clue where and why the schema is modified in the middle.

**Comment by hasezoey** [comment]
i made a review of the repo in https://github.com/OoDeLally/typegoose-inheritance-bug/issues/1, please answer the questions & "wrong things" there, thanks

-> if i can confirm this behavior and not as "user error", i will re-tag this

**Comment by OoDeLally** [comment]
Wow thank you for the quick answer! I'll review this and let you know.

**Comment by hasezoey** [comment]
@OoDeLally are your issues / questions solved?

**Comment by OoDeLally** [comment]
Hi @hasezoey , Yes, the problem doesnt occur when `_id` is not declared as part of the properties.
I guess the problem will be solved at the same time as https://github.com/typegoose/typegoose/issues/81, so I'm closing this one.
Cheers!
